/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.AlumnoData;
import java.awt.HeadlessException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Conexion;
import modelo.Materia;

/**
 *
 * @author Caro_Z
 */
public class ViewListadoDeAlumnos extends javax.swing.JInternalFrame {

    Conexion conexion = new Conexion();

    private ArrayList<Alumno> listaAlumnosA;
    private ArrayList<Alumno> listaAlumnosI;
    private AlumnoData alumnoData;
    private DefaultTableModel modelo;

    public ViewListadoDeAlumnos() {
        initComponents();
        this.setSize(700, 550);
       
      
        alumnoData = new AlumnoData(conexion);

        conexion = new Conexion();
        alumnoData = new AlumnoData(conexion);
        listaAlumnosA = (ArrayList<Alumno>) alumnoData.listarAlumnosActivos();
        listaAlumnosI = (ArrayList<Alumno>) alumnoData.listarAlumnosInactivos();

        modelo = new DefaultTableModel();
        armaCabeceraTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        rbActivos = new javax.swing.JRadioButton();
        rbNoActivos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        btAlta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_form_institucion.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTADO DE ALUMNOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 60, 276, 29);

        rbActivos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rbActivos.setForeground(new java.awt.Color(0, 0, 153));
        rbActivos.setText("ACTIVOS");
        rbActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivosActionPerformed(evt);
            }
        });
        getContentPane().add(rbActivos);
        rbActivos.setBounds(460, 180, 73, 21);

        rbNoActivos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rbNoActivos.setForeground(new java.awt.Color(0, 0, 153));
        rbNoActivos.setText("NO ACTIVOS");
        rbNoActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActivosActionPerformed(evt);
            }
        });
        getContentPane().add(rbNoActivos);
        rbNoActivos.setBounds(170, 180, 91, 21);

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "APELLIDO", "NOMBRE", "FECHA DE NAC", "ACTIVO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tAlumnos);
        if (tAlumnos.getColumnModel().getColumnCount() > 0) {
            tAlumnos.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 540, 160);

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(460, 430, 77, 32);

        btAlta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAlta.setText("DAR DE ALTA");
        btAlta.setEnabled(false);
        btAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltaActionPerformed(evt);
            }
        });
        getContentPane().add(btAlta);
        btAlta.setBounds(110, 430, 189, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_form_institucion.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-23, -9, 740, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivosActionPerformed
        // TODO add your handling code here:
        rbNoActivos.setSelected(false);
        btAlta.setEnabled(false);
        borraFilasTabla();
        cargaDatosActivos();


    }//GEN-LAST:event_rbActivosActionPerformed

    private void rbNoActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActivosActionPerformed
        // TODO add your handling code here:
        rbActivos.setSelected(false);

        borraFilasTabla();
        cargaDatosInactivos();
        btAlta.setEnabled(true);

    }//GEN-LAST:event_rbNoActivosActionPerformed

    private void btAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltaActionPerformed
        // TODO add your handling code here:
        try {
            int filaSeleccionada = tAlumnos.getSelectedRow();

            if (filaSeleccionada != -1) {

                int id_alumno = (Integer) modelo.getValueAt(filaSeleccionada, 0);
                String apellido = (String) modelo.getValueAt(filaSeleccionada, 1);
                String nombre = (String) modelo.getValueAt(filaSeleccionada, 2);

                alumnoData.activarAlumno(id_alumno);

                boolean estado = (Boolean) modelo.getValueAt(filaSeleccionada, 4);

                borraFilasTabla();

            } else {
                JOptionPane.showMessageDialog(this, " Debe seleccionar un alumno");

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, " No se puedo dar de alta el alumno");
        }
    }//GEN-LAST:event_btAltaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed
    private void armaCabeceraTabla() {

        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Apellido");
        columnas.add("Nombre");
        columnas.add("Fecha de Nac");
        columnas.add("Activo");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        tAlumnos.setModel(modelo);
    }

    private void borraFilasTabla() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    private void cargaDatosActivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Alumno> lista = (ArrayList) alumnoData.listarAlumnosActivos();

        for (Alumno a : lista) {

            modelo.addRow(new Object[]{a.getId_alumno(), a.getApellido(), a.getNombre(), a.getFechaNac(), a.isActivo()});
        }
    }

    private void cargaDatosInactivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Alumno> lista = (ArrayList) alumnoData.listarAlumnosInactivos();

        for (Alumno a : lista) {

            modelo.addRow(new Object[]{a.getId_alumno(), a.getApellido(), a.getNombre(), a.getFechaNac(), a.isActivo()});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlta;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbActivos;
    private javax.swing.JRadioButton rbNoActivos;
    private javax.swing.JTable tAlumnos;
    // End of variables declaration//GEN-END:variables
}
