/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import vistas.ViewAlumnos;
import vistas.ViewCargaDeNotas;
import vistas.ViewFormularioInscripcion;
import vistas.ViewListadoDeAlumnosPorMateria;
import vistas.ViewMaterias;

/**
 *
 * @author salva
 */
public class ViewInstitucion extends javax.swing.JFrame {

    /**
     * Creates new form Institucion
     */
    public ViewInstitucion() {
        initComponents();
     
        this.setSize(700, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel8 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiFormularioDeMaterias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiFormularioDeAlumnos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiManejoDeInscripciones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiManipulacionDeNotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiListadoDeAlumnosporMateria = new javax.swing.JMenuItem();
        jmConsultasNotasAlumnos = new javax.swing.JMenuItem();
        jlistadoDeMateriasPorAlumnos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        listarMaterias = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        escritorio.add(jLabel2);
        jLabel2.setBounds(420, 310, 220, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_form_institucion.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        escritorio.add(jLabel1);
        jLabel1.setBounds(-20, 0, 790, 610);

        getContentPane().add(escritorio);
        escritorio.setBounds(0, 0, 760, 590);

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Archivo");

        jmiSalir.setBackground(new java.awt.Color(255, 255, 255));
        jmiSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(0, 0, 153));
        jMenu3.setText("Materias");

        jmiFormularioDeMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiFormularioDeMaterias.setText("Formulario de materias");
        jmiFormularioDeMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioDeMateriasActionPerformed(evt);
            }
        });
        jMenu3.add(jmiFormularioDeMaterias);

        jMenuBar1.add(jMenu3);

        jMenu2.setForeground(new java.awt.Color(0, 0, 153));
        jMenu2.setText("Alumnos");

        jmiFormularioDeAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiFormularioDeAlumnos.setText("Formulario de alumnos");
        jmiFormularioDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioDeAlumnosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFormularioDeAlumnos);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(0, 0, 153));
        jMenu4.setText("Inscripciones");

        jmiManejoDeInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiManejoDeInscripciones.setText("Manejo de inscripciones");
        jmiManejoDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoDeInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(jmiManejoDeInscripciones);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 0, 153));
        jMenu5.setText("Carga De Notas");

        jmiManipulacionDeNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiManipulacionDeNotas.setText("Manipulación de notas");
        jmiManipulacionDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManipulacionDeNotasActionPerformed(evt);
            }
        });
        jMenu5.add(jmiManipulacionDeNotas);

        jMenuBar1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(0, 0, 153));
        jMenu6.setText("Consultas");

        jmiListadoDeAlumnosporMateria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiListadoDeAlumnosporMateria.setText("Listado de Alumnos por Materia");
        jmiListadoDeAlumnosporMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListadoDeAlumnosporMateriaActionPerformed(evt);
            }
        });
        jMenu6.add(jmiListadoDeAlumnosporMateria);

        jmConsultasNotasAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmConsultasNotasAlumnos.setText("Notas de Alumnos");
        jmConsultasNotasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultasNotasAlumnosActionPerformed(evt);
            }
        });
        jMenu6.add(jmConsultasNotasAlumnos);

        jlistadoDeMateriasPorAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlistadoDeMateriasPorAlumnos.setText("Listado de Materias por Alumnos");
        jlistadoDeMateriasPorAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistadoDeMateriasPorAlumnosActionPerformed(evt);
            }
        });
        jMenu6.add(jlistadoDeMateriasPorAlumnos);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Listado de Alumnos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        listarMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listarMaterias.setText("Listado de Materias");
        listarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMateriasActionPerformed(evt);
            }
        });
        jMenu6.add(listarMaterias);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormularioDeMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioDeMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewMaterias vm = new ViewMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_jmiFormularioDeMateriasActionPerformed

    private void jmiFormularioDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioDeAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewAlumnos va = new ViewAlumnos();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_jmiFormularioDeAlumnosActionPerformed

    private void jmiManejoDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoDeInscripcionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormularioInscripcion vfi = new ViewFormularioInscripcion();
        vfi.setVisible(true);
        escritorio.add(vfi);
        escritorio.moveToFront(vfi);
    }//GEN-LAST:event_jmiManejoDeInscripcionesActionPerformed

    private void jmiManipulacionDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManipulacionDeNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewCargaDeNotas vcn = new ViewCargaDeNotas();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_jmiManipulacionDeNotasActionPerformed

    private void jmiListadoDeAlumnosporMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListadoDeAlumnosporMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewListadoDeAlumnosPorMateria vlapm = new ViewListadoDeAlumnosPorMateria();
        
                
        vlapm.setVisible(true);
        escritorio.add(vlapm);
        escritorio.moveToFront(vlapm);
    }//GEN-LAST:event_jmiListadoDeAlumnosporMateriaActionPerformed

    private void jmConsultasNotasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultasNotasAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewConsultasNotasDeAlumnos cna= new  ViewConsultasNotasDeAlumnos();
        cna.setVisible(true);
        escritorio.add(cna);
        escritorio.moveToFront(cna);
        
        
        
    }//GEN-LAST:event_jmConsultasNotasAlumnosActionPerformed

    private void jlistadoDeMateriasPorAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistadoDeMateriasPorAlumnosActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        ViewListadoDeMateriasPorAlumno lm= new  ViewListadoDeMateriasPorAlumno();
        lm.setVisible(true);
        escritorio.add(lm);
        escritorio.moveToFront(lm);
        
        
        
        
    }//GEN-LAST:event_jlistadoDeMateriasPorAlumnosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
       ViewListadoDeAlumnos la= new  ViewListadoDeAlumnos();
        la.setVisible(true);
        escritorio.add(la);
        escritorio.moveToFront(la);
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void listarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
       ViewListadoDeMaterias lnm= new  ViewListadoDeMaterias();
        lnm.setVisible(true);
        escritorio.add(lnm);
        escritorio.moveToFront(lnm);
        
        
        
    }//GEN-LAST:event_listarMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInstitucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem jlistadoDeMateriasPorAlumnos;
    private javax.swing.JMenuItem jmConsultasNotasAlumnos;
    private javax.swing.JMenuItem jmiFormularioDeAlumnos;
    private javax.swing.JMenuItem jmiFormularioDeMaterias;
    private javax.swing.JMenuItem jmiListadoDeAlumnosporMateria;
    private javax.swing.JMenuItem jmiManejoDeInscripciones;
    private javax.swing.JMenuItem jmiManipulacionDeNotas;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem listarMaterias;
    // End of variables declaration//GEN-END:variables
}
