/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.MateriaData;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.Materia;

/**
 *
 * @author salva
 */
public class ViewMaterias extends javax.swing.JInternalFrame {
    private MateriaData materiaData;
    private Conexion conexion;
    /**
     * Creates new form ViewMaterias
     */
    public ViewMaterias() {
        initComponents();
        this.setSize(700, 550);
        conexion = new Conexion();
        materiaData = new MateriaData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jbBusccar = new javax.swing.JButton();
        jCheckBoxEstado = new javax.swing.JCheckBox();
        jbGuardar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jtfAño = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MATERIAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 140, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(115, 135, 76, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(111, 208, 80, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AÑO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(151, 282, 40, 22);

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfCodigo);
        jtfCodigo.setBounds(263, 139, 75, 30);

        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtfNombre);
        jtfNombre.setBounds(263, 202, 290, 30);

        jbBusccar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbBusccar.setText("BUSCAR");
        jbBusccar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusccarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBusccar);
        jbBusccar.setBounds(446, 137, 90, 30);

        jCheckBoxEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxEstado.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxEstado.setText("ESTADO");
        getContentPane().add(jCheckBoxEstado);
        jCheckBoxEstado.setBounds(440, 285, 72, 24);

        jbGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbGuardar.setText("GUARDAR");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar);
        jbGuardar.setBounds(110, 390, 105, 34);

        jbBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbBorrar.setText("BORRAR");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBorrar);
        jbBorrar.setBounds(370, 450, 110, 34);

        jbActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jbActualizar);
        jbActualizar.setBounds(370, 390, 108, 34);

        jbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimpiar.setText("LIMPIAR");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpiar);
        jbLimpiar.setBounds(110, 450, 110, 34);

        jtfAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAñoFocusLost(evt);
            }
        });
        jtfAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAñoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfAño);
        jtfAño.setBounds(263, 276, 64, 30);

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir);
        jbSalir.setBounds(580, 420, 101, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(49, 362, 702, 2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_form_institucion.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -10, 870, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBusccarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusccarActionPerformed
        // TODO add your handling code here:
        Materia m = materiaData.buscarMateria(Integer.parseInt(jtfCodigo.getText()));
        if(m != null){
        jtfNombre.setText(m.getNombre());
        jtfAño.setText(m.getAnio()+"");
        jCheckBoxEstado.setAutoscrolls(m.isActivo());
        jbGuardar.setEnabled(false);
        jbBorrar.setEnabled(true);
        jbActualizar.setEnabled(true);
        }
    }//GEN-LAST:event_jbBusccarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        
        String nombre = jtfNombre.getText();
        int anio = Integer.parseInt(jtfAño.getText());
        Materia m = new Materia(nombre, anio, jCheckBoxEstado.isSelected());
        materiaData.agregarMateria(m);
        jtfCodigo.setText(m.getId_materia()+"");
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jtfCodigo.setText("");
        jtfNombre.setText("");
        jtfAño.setText("");
        jCheckBoxEstado.setSelected(false);
        jbGuardar.setEnabled(true);
        jbBorrar.setEnabled(true);
        jbActualizar.setEnabled(true);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(jtfCodigo.getText());
        if(materiaData.materiaExiste(id)){
            materiaData.eliminarMateria(id);
            jbGuardar.setEnabled(false);
            jbActualizar.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "Materia no existente");
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if (jtfCodigo.getText() != null){
            int id = Integer.parseInt(jtfCodigo.getText());
            String materia = jtfNombre.getText();
            int anio = Integer.parseInt(jtfAño.getText());
            boolean activo = jCheckBoxEstado.isSelected();
            Materia m = new Materia(materia,anio,activo);
            materiaData.modificarMateria(id, m);
            jbGuardar.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "Materia ya actualizada");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:

  
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        // TODO add your handling code here:
        if (jtfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Nombre debe estar completo");
            jtfNombre.requestFocus();
        }
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfAñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAñoFocusLost
        // TODO add your handling code here:
        if (jtfAño.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Año debe estar completo");
            jtfAño.requestFocus();
        }else{
            jbGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_jtfAñoFocusLost

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            JOptionPane.showMessageDialog(this,"El Codigo debe ser numérico");
            evt.consume();
        }        
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void jtfAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAñoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            JOptionPane.showMessageDialog(this,"El Año debe ser numérico");
            evt.consume();
        }    
    }//GEN-LAST:event_jtfAñoKeyTyped

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBusccar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtfAño;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
